### ISSUE TITLE
情報解禁に向けて告知

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#19]
https://twitter.com/kasaikouhei/status/1381591132002340866?s=19

などで告知開始

**Comment by miyayuki** [comment]
いい感じ
https://twitter.com/kasaikouhei/status/1383575761232138253?s=19

**Comment by kasaikouhei** [comment]
情報解禁Tweet文案：

--------------
同人誌「特集：原稿料」という呼んでいた企画を、「作家の手帖」と題して始めます。編集長は、笠井康平と小澤みゆきが務めます。

執筆・登壇・制作スタッフ募集と、原稿料にまつわる体験談の受付は今月末まで。予約購入もできます。 

企画書はこちらからご覧ください。
https://writer-life-committee.github.io/authors-note/
--------------

**Comment by miyayuki** [comment]
滑り出しはよいのではないか。情報解禁後のツイートアクティビティやPV、コンバージョン数などを計測しておき、収支計算に入れる。
