### ISSUE TITLE
STORESのオープン

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#20]
情報解禁とともに有料チケットも告知、Github Pagesからリンクさせる

**Comment by miyayuki** [comment]
・プライバシーポリシーをリンク
・商品説明を加筆
・購入者向けメッセージを加筆
・GAの導入

**Comment by miyayuki** [comment]
ショートピッチ参加券を入れた有料チケットの作成

**Comment by kasaikouhei** [comment]
商品ページを加筆したら終わり。商品ページには参加規約のリンクもつけること

**Comment by miyayuki** [comment]
無事オープン。
