### ISSUE TITLE
領収書の発行

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#29]
希望者のみに発行。misocaを試してみたが、デザインがいまいちなので、要検討。

**Comment by kasaikouhei** [comment]
EReceipt（イーレシート）が便利で、デザインもよさそう。利用規約も問題なし。
https://www.ereceipt.jp/

**Comment by miyayuki** [comment]
送信文のテンプレートを作成。

---
XX さま

こんにちは、「作家の手帖」編集長の小澤みゆきです。
この度は、「作家の手帖」準備号購読チケット（一般）のご購入をありがとうございました。

領収書をPDFファイルにてお送りいたしますので、下記URLからダウンロードをお願いします。
http://~~~
ご査収のほどよろしくお願いいたします。

PDFファイルの内容が見れないなどの不備がございましたら、
お手数ですがご一報いただけますでしょうか。

今後とも、「作家の手帖」をよろしくお願いいたします。

文筆生活向上委員会（代表：笠井康平・小澤みゆき）
writer.life.committee[at]gmail.com

**Comment by miyayuki** [comment]
現時点での希望者には送付済み。今後、制作事務のスタッフの方にお願いしていく。
