### ISSUE TITLE
Web サイト環境の整備

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#31]
Higo+Netfilyという方法を教えてもらった
https://qiita.com/jrfk/items/4c6df87ca72a76e30224

**Comment by miyayuki** [comment]
少し気が早いが、第1号を今秋から始めるとそろそろ真面目に考えたほうがよさそう。ドメインは変えたくないが、デザインはリニューアル（メインビジュアルに合わせて水色基調？）&CMS化したい。

**Comment by paina** [comment]
> ドメインは変えたくないが

GitHub Pages (github.io) を使い続けるかんじでしょうか。

**Comment by miyayuki** [comment]
> GitHub Pages (github.io) を使い続けるかんじでしょうか。
はい、できればそうしたいですー（リンク切れを防ぐため）

**Comment by miyayuki** [comment]
つくりました。
https://github.com/Writer-Life-Committee/authors-note-webtest
これ移行は別issueで管理しようと思います。
