### ISSUE TITLE
ガントチャート作成ツールを導入

### ISSUE THREAD

**Issue by kasaikouhei** [Writer-Life-Committee/authors-note#34]
・ガントチャート更新を省力できること（必須）
・少なくとも両編集長が閲覧できること（必須）
・できれば執筆者・制作スタッフ全員が共同閲覧できること（なるべく）
・GithubのIssuesと連携できること（なるべく）
・Githubのアドオンであること（もしできれば）
・執筆者・制作スタッフがみずから予定登録できること（もしできれば）

**Comment by miyayuki** [comment]
GithubのIssuesと連携できるサービス

Zenhub
https://www.zenhub.com
月$7.95。14日無料。

Elegant for Trello
https://elegantt.com/
Chromeエクステンション。無料。

試して見るなら後者？
あと、GitHub Projectsをまったくつかいこなせていないので、これでカンバンをやってみるのもあり（ガントチャート機能はないが）

**Comment by kasaikouhei** [comment]
GitHub Projectsを試してみましょう。

Elegant for Trelloを試す価値はあり、調べたところ、GitHub IssuesとTrelloを同期する方法はあるよう（API叩く必要ある）
https://qiita.com/Tommydevelop/items/e26654447e43edd4286e

**Comment by miyayuki** [comment]
ZenHubを使ってみたが、
- Roadmap（いわゆるガンチャ機能）がかゆいところに手が届かない
- そもそもログインしないと見れず、一般公開できない
ため、ちょっと無理そう。基本に立ち返ってGitHub Projectsを使い倒しましょう。
