### ISSUE TITLE
Pull Requestをくれた方の謝辞を掲載

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#37]

**Comment by kasaikouhei** [comment]
月城さんに渡したテキスト素材には、先々週時点でPull Requestをくれた方のGitHubネームを加えてある。スタッフリストのなかのスペシャルサンクス。

**Comment by kasaikouhei** [comment]
先週時点までにPull Requestくれた方のGithubネームを追加済。これにてクローズ。
