### ISSUE TITLE
CCライセンスの再検討

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#38]
いま、[CC-BY-ND-NC 4.0（表示・非営利・改変禁止 4.0 国際）](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ja)にしているが、このままだとリポジトリのforkやcloneはできても、Pull Requestができない可能性がある。

**Comment by kasaikouhei** [comment]
CC-BY-NC 4.0に切り替える。
