### ISSUE TITLE
デザインコンセプトシートの作成

### ISSUE THREAD

**Issue by kasaikouhei** [Writer-Life-Committee/authors-note#45]
・デザイナー（月城さん）にお見せするもの。ざっくりした要件定義書。
・このWebマガジンの性格、スタイル、読者に伝えたい印象、メッセージなどをまとめる。
・既定の文字要素その他の情報も盛り込む。
・せっかくなので封筒や紙選びにも凝ってはどうかという案も。

**Comment by miyayuki** [comment]
作成中で、デザイナーの月城さんと調整中。

**Comment by kasaikouhei** [comment]
作成したデザインコンセプトシートをもとに、月城さんから3案のコンセプトをもらい、大まかな方針決定。テキスト素材を渡し、デザイン原稿の作成を進めてもらっているところ

**Comment by kasaikouhei** [comment]
[こちら](https://docs.google.com/document/d/1b0mfiZ1ul98g7tVhUpXDmIk_fp2DoOokaeZga9hBFEU/edit)に作成。あとでGitHubにもあげておく。デザインが決まり、細部の詰めに入っている。
