### ISSUE TITLE
勉強会の進行台本

### ISSUE THREAD

**Issue by kasaikouhei** [Writer-Life-Committee/authors-note#48]
番組プログラムはできているので、時間帯ごとの確認事項をスプレッドシートなどにまとめる

**Comment by kasaikouhei** [comment]
第2部のうち、野村・竹中回を小澤さんが作成。熱海さん回は笠井が作成に着手。それが終わったら第3部をつくる（登壇順も含め）。

**Comment by kasaikouhei** [comment]
熱海さん回の進行台本ができた。第3部に着手する

**Comment by miyayuki** [comment]
第3部を作成中

**Comment by miyayuki** [comment]
進行台本（全体、me and you回、熱海回）は完成済み。出演者へのURL送付も済んでいる。
リハーサルの結果も記載。painaさんによる技術メモも記載している。
完璧！

**Comment by miyayuki** [comment]
時間割ページに、当日の出演順やプログラム案を追記。
https://writer-life-committee.github.io/authors-note/event-vol1.html
