### ISSUE TITLE
印刷・封入・発送の外注先を探す

### ISSUE THREAD

**Issue by kasaikouhei** [Writer-Life-Committee/authors-note#59]
皐月さん・小澤さんと話して決める。予算節約のために、最終的な印刷枚数は購読チケット枚数に応じて決めたい。第一弾の封入・発送は、いざとなれば編集長が内職すればいいかと思ったりもする。

**Comment by kasaikouhei** [comment]
いまの購入数だと、
・招待状は印刷発注（ちょっといい紙）
・封筒・宛名ラベルは小売で購入
・編集長が封入・封緘
・料金別納郵便スタンプを買って押印
としたほうが、トータルの単価が下がる見込み。

**Comment by paina** [comment]
宛名ラベルの印刷は必要であれば @paina が実施します。

**Comment by kasaikouhei** [comment]
宛名ラベル、秋葉原に印刷サービスがあるようで、そちらを使おうと思います。
・封筒、宛名ラベル、料金別納シールは注文分を受取済。
・招待状の印刷は注文・入稿済で、8/16に京都から発送予定。
