### ISSUE TITLE
Zoomの設定

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#65]
委員会のアカウントは作った。

**Comment by miyayuki** [comment]
1ヶ月限定でZoomのプロアカウントにアップグレード（¥2,200）。ウェビナーのライセンス料がさらに¥10,700するため、どうするか悩み中。技術部で相談して決める。

**Comment by paina** [comment]
定員 100 人の 5,000 円くらいのライセンスがあったのですが，2021 年 7 月ごろ廃止された模様。
https://support.zoom.us/hc/ja/articles/4402813380493

ひとまずは Webinar ではなく Meeting でやることにして，事前にミュートなどの機能を確認しておく。
この Issue を self-assign しました。

# 早めに買っておいたら安いライセンス料金で定員 500 人になったのですね。ぐぬぬ。

**Comment by paina** [comment]
Zoom 以外のプラットフォーム，具体的には Amazon Chime (https://chime.aws/) などを検討したが，正直ちょっと「とっつきづらそう」だった。
根性で Zoom のミーティング（ウェビナーではない形式）でやってみましょう。

**Comment by miyayuki** [comment]
リハーサルの結果、Zoomミーティングで今回はいけそう。本番URLをpainaさんに発行依頼。

**Comment by miyayuki** [comment]
painaさんが本番URL発行済。出演者・読者に告知します。
