### ISSUE TITLE
勉強会リハーサルの読者限定公開

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#68]
今週末（8/14,15）に実施予定のリハーサルを、有料購読者限定で公開するのはどうか。
運営的には実環境に近い状況でテストできるのと、読者にとってイベント開催ノウハウの参考になるかもしれない。
来てくださった方限定で笠井さんのトーク練習（小話？）するのもよさそう。

**Comment by kasaikouhei** [comment]
小澤さんが投稿済
