### ISSUE TITLE
勉強会ショートスピーチ参加の方への連絡

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#72]
- 日程・時間の確認
- 団体規約の共有
- 当日話してもらう内容をざっくりヒアリング（できれば）
- 可能なら、リハーサルへの参加

**Comment by kasaikouhei** [comment]
こちらと重複のためクローズ：
https://github.com/Writer-Life-Committee/authors-note/issues/64

**Comment by miyayuki** [comment]
ショートスピーチ各位に連絡はしているが、まだ返信なし。本番URLをメール送付時に、要返信とし、出血席を確定させる。
