### ISSUE TITLE
招待状の宛名ラベル作成

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#75]
8/14,15に宛名ラベル印刷。
対象者は
- STORES購入者
- 執筆者・登壇者・制作スタッフ
- 資料提供者（2名）

8/18以降には招待状を発送に着手予定。
8/19以降に購入した人にも、勉強会本番後になるが、招待状は届く。

購入者は、以下が入手できる。
- 完成稿PDF/epub
- テキストアーカイヴ（Google Drive）閲覧
- Discord招待
- 動画アーカイヴ
- 次回勉強会（時期未定）の参加

**Comment by kasaikouhei** [comment]
8/15に以下をやる
・宛名ラベルのデータ作成
・[クリエーターズカフェ秋葉原製作所](http://www.seisakujo.com/charge/print.php)のペーパー印刷で出力

**Comment by kasaikouhei** [comment]
・差出人ラベルのデータも作っておくとよい

**Comment by miyayuki** [comment]
宛名ラベル・差出人ラベルともにデータ作成完了。
3Mの「ラベル屋さん」ツールを仕様。
csv・Excelインポートはウェブ版では使えずローカルアプリを使用。またアプリが重くUIも若干使いづらいため、デザインが消えてしまい数回やり直した。
が、Wordなどで作るよりはましか。
https://www.labelyasan.com/
