### ISSUE TITLE
勉強会の音楽・SE

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#76]
- ジングル
- 待機用音楽
- 銅鑼（ショートスピーチ用）
- トーク中のチルっぽい音楽

などがあればかっこいいが、フリー音源でどこまでできるか検討。

**Comment by paina** [comment]
Zoom の仕様で，誰かが画面共有していると他の参加者が computer sound share できないと分かった。
仮想オーディオインターフェースなどでうまくできないか検討する。

**Comment by paina** [comment]
わりとさっくりできた！

- VB-CABLE（仮想オーディオデバイス）をインストールする
  https://vb-audio.com/Cable/index.htm
- PC の音声の出力先を CABLE Input に，Zoom の入力を CABLE Output にする
- Zoom の出力先を Same as System と CABLE Input 以外の適当なやつにして音量をゼロにする
- Zoom の Audio Settings の "Music and Professional Audio" なる設定をオンにする
  いまのところ設定は下記の通り
  - High fidelity music mode: On
  - Echo cancellation: Off
  - Stereo audio: Off
- Zoom のミーティングの画面で "Original Sound" を On にするのを忘れない

SE のポン出しには効果音ラボの Web のアプリが便利そう。
https://soundeffect-lab.info/pon/

他，Tips:

- Windows の Volume Mixer で必要なアプリ以外をミュートしておくと誤爆が防げそう
- 仮想デバイスのボリュームは調整不能（ミュートか 100% かになる）

なお，これをやるには専用の PC がいるので，技術担当 (paina) はやっぱり複数 PC から参加する。

**Comment by paina** [comment]
## 待機音楽候補 - 2021/08/17
- 「楽しげに誰かがやってくる時のテーマ」（すごいタイトルだ）
  https://www.hurtrecord.com/bgm/93/tanoshige-ni-dareka-ga-yattekurutoki-no-theme.html
- 「キラリきらめく」
  https://dova-s.jp/bgm/play2807.html
- 「HIKARI」
  https://soundcloud.com/baron1_3/hikari

うーんもうちょっとテレビっぽいのが欲しいかも。
ちなみにこれはサブスクが年間契約で高くて買えなかったが，けっこうよかったやつ。
- https://artlist.io/jp/song/48542/slime-time

もう少し探します!!

**Comment by paina** [comment]
## 2021/08/18 さがしたもの

このサイトよさそう: https://www.fesliyanstudios.com/
ただ本プロジェクトでの利用が「商用」にあたるかどうかが要検討。それでも少額の寄付で Ok そう。
いずれにしても，日本語サイトじゃなく英語サイトで探したほうが探しやすくマスも多いと気づいてきた。

### 待機音楽候補

待機音楽は可能なら，数曲選んでループしたい。

- 「Feeling The Best」
  これいいかもしれない，夏っぽくて。
  https://www.fesliyanstudios.com/royalty-free-music/download/feeling-the-best/484
- 「the opening of a book」
  https://dova-s.jp/bgm/play2870.html

### ジングル候補
- 「大当たり！」
  但し CC-BY。
  https://otologic.jp/free/jing/long1.html

**Comment by miyayuki** [comment]
ジングル、漫才の出囃子感あってかなりいいですね

**Comment by paina** [comment]
ジングルはひとまずこれにしましょうかね。
CC-BY なので，最終決定したらタイトルスライドかどこかにクレジットを入れておきます。

**Comment by miyayuki** [comment]
決定したらevent-vol1.mdに追記しましょう。

**Comment by paina** [comment]
了解。限定公開の配信からもそこにリンクするかたちにします。

**Comment by paina** [comment]
SE（効果音）ポン出しシステム，できそう。

![PXL_20210820_074737214 - Copy](https://user-images.githubusercontent.com/962134/130200695-f00d0eca-302d-4678-91d7-85c339894a3c.jpg)

ソフトは Soundplant ってのがよさそうだった。
https://soundplant.org/

キーパッド（テンキー）はサンワサプライ NT-19UH2BKN。
プログラマブルでキーに機能を割り付けられるんだけれど，今回はただのテンキーとして使っている。
キーのカバーがついていて中にメモを入れられる。おもしろい。
https://www.sanwa.co.jp/product/syohin.asp?code=NT-19UH2BKN

**Comment by miyayuki** [comment]
ポン出しキーボードすばらしいです。ありがとうございます！
効果音・BGMもすべて聞きました。
進行台本にも、いつどの音を流すか追記済み。

**Comment by miyayuki** [comment]
最終リハでチェック済み。音量の調節、painaさんよろしくお願いします！
