### ISSUE TITLE
招待状の発送

### ISSUE THREAD

**Issue by kasaikouhei** [Writer-Life-Committee/authors-note#78]
■発送までの流れ
・8/15に宛名ラベルを印刷。
・8/16に招待状が出荷。
・8/17-8/18頃に招待状を受取（見込）
・8/16-8/18にかけて封筒のシール貼
・8/19（午前中）に郵便局へ持ち込み
・8/20-8/21に購読者に届く（予定）

■シール貼・封入・封緘の流れ
・料金別納郵便シールを貼る
・宛名ラベルを貼る
・差出人ラベルを貼る
・招待状を封入する
・アラビア糊を水で濡らして封緘

**Comment by miyayuki** [comment]
8/17 発送済み。早い方には明日届くかもしれない？
