### ISSUE TITLE
完成稿のPDF/ePubファイルを作成

### ISSUE THREAD

**Issue by miyayuki** [Writer-Life-Committee/authors-note#88]
PDFは、InDesignで組めないか試し中（小澤）。
ePubは、Docsをでんでんコンバーターに流し込んで作成（笠井）。

**Comment by miyayuki** [comment]
inDesignで組むのはやっぱ大変なので、全部入りのDocsを作ってそれをPDF化することにした。

**Comment by paina** [comment]
PDF，Pandoc でやってみましょうか？

**Comment by miyayuki** [comment]
@paina すみません、PDFはGoogle Docsから作ってしまいました。
ePubもDocsから直接ダウンロードできたため解決。
できた！
