### ISSUE TITLE
個別の依頼状をつくる

### ISSUE THREAD

**Issue by kasaikouhei** [Writer-Life-Committee/authors-note#9]
依頼書に相当

**Comment by kasaikouhei** [comment]
共通依頼書と依頼状（個別）をつくる。依頼状には、執筆者におねがいすることを箇条書きにする。

・規約類の通読
・修正希望があれば改訂案（共通規約を改訂するか仕様書で特約とするか判断）
・応募フォームから草案・プロフィール・打合せ希望日を提出
・仕様書の加筆・修正希望
・キックオフ打合せ、個別打合せに出席
・発注書へ承諾の返信
・草稿の執筆
・編集稿の確認
・校正稿の確認
・勉強会の出演
・請求書の発行

**Comment by kasaikouhei** [comment]
編集長（笠井）自身も、ひとりの執筆者として一連の仕事をする。このとき、各作業の所要時間を測っておき、依頼内容に無理がないか、次号で改善すべきところがあるかを考える材料にする。

**Comment by kasaikouhei** [comment]
ただし、規約類を書いた笠井は、リーガル文書を読み慣れており、通読時間を測っても有力な参考にならないことは明らか。小澤にも読んでもらい、その時間も目安にする。

**Comment by kasaikouhei** [comment]
issue18が共通依頼書のタスクで、こちらは個別の依頼状とする。個別の依頼状は、執筆希望の方への当選連絡を兼ねる。こちらから依頼したい方ーー制作スタッフを含めーーの仕様書を案内するメール本文でもある。

個別の依頼状は、共通テキストを公表する。私信に近いやりとりは営業秘密に当たるから、執筆者の希望と同意がなければ公表しないほうがいい。

同意だけではなく、希望が必要。書簡や日記を公にするようなものだから、いくらか手直しをしたり、割愛することにもなる。これ自体がひとつの執筆企画なのだろうし、省力のためにも今回はやらないほうが賢明。

**Comment by kasaikouhei** [comment]
応募者のみなさんにお礼をメール（5/2）。個別依頼状を作成し、それぞれに送付（5/3-5/4）。合わせて打合せ依頼する。

**Comment by miyayuki** [comment]
（ぜっさん作業中）

**Comment by miyayuki** [comment]
（依頼上の送付完了、打ち合わせ調整へ）

**Comment by miyayuki** [comment]
（まだまだまだまだ作業中）

**Comment by miyayuki** [comment]
（依頼状の送付は終了し、週末で打ち合わせを個別に実施）

**Comment by kasaikouhei** [comment]
閉じ忘れ
